name: 'Build and Deploy to GKE'

on:
  push:
    branches:
      - 'main'  # Removed unnecessary quotes

env:
  PROJECT_ID: 'my-project' 
  GAR_LOCATION: 'us-central1'
  GKE_CLUSTER: 'cluster-1'
  GKE_ZONE: 'us-central1-c'
  DEPLOYMENT_NAME: 'gke-test'
  REPOSITORY: 'samples'
  IMAGE: 'static-site'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'

jobs:
  build-and-deploy:
    name: 'Build and Deploy'
    runs-on: 'ubuntu-latest'
    environment: 'production'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout Repository'
        uses: 'actions/checkout@v4'  # Use version tag instead of commit hash

      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'  # Updated to latest stable version
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: 'deployment-service-account@my-project.iam.gserviceaccount.com'  # Recommended best practice

      - name: 'Configure Docker for GAR'
        uses: 'docker/login-action@v3'
        with:
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'  # More secure output name

      - name: 'Configure GKE Access'
        uses: 'google-github-actions/get-gke-credentials@v1'  # Updated version
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          location: '${{ env.GKE_ZONE }}'
          project_id: '${{ env.PROJECT_ID }}'  # Explicit project specification

      - name: 'Build and Push Docker Image'
        run: |-
          DOCKER_TAG="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:${GITHUB_SHA}"
          docker build \
            --tag "$DOCKER_TAG" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .
          docker push "$DOCKER_TAG"

      - name: 'Install Kustomize'
        uses: 'imranismail/setup-kustomize@v1'  # Better installation method
        with:
          kustomize-version: 'v5.4.3'

      - name: 'Deploy to GKE'
        run: |-
          # Update image reference in manifests
          kustomize edit set image \
            "LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG=${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}"
          
          # Apply configuration
          kustomize build . | kubectl apply -f -
          
          # Verify deployment
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} --timeout=5m
          kubectl get services -o wide

      - name: 'Verify Service URL'
        run: |
          echo "Application deployed at: $(kubectl get service ${{ env.DEPLOYMENT_NAME }}-svc -o jsonpath='{.status.loadBalancer.ingress[0].ip}')"
